apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-microshift-gitops
spec:
  clusterSets:
  - microshift
  predicates:
  - requiredClusterSelector:
      claimSelector:
        matchExpressions:
        - key: product.open-cluster-management.io
          operator: In
          values:
            - Microshift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-microshift-gitops
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-microshift-gitops
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: microshift-gitops
