apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gitops-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-gitops"
policies:
  - name: policy-microshift-gitops
    remediationAction: enforce
    manifests:
      - path: manifests/gitops/argocd
  - name: policy-microshift-bootstrap
    remediationAction: enforce
    manifests:
      - path: manifests/gitops/bootstrap
policySets:
  - name: "microshift-gitops"
    description: "Policy for bootstrapping cluster with gitops"
    policies:
      - policy-microshift-gitops
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-microshift-gitops
