apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt-aws
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: letsencrypt-aws
  data:
    - secretKey: secret-access-key
      remoteRef:
        key: AWS_LETSENCRYPT
