apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
  name: router-default
  namespace: openshift-ingress
spec:
  template:
    spec:
      volumes:
      - name: default-certificate
        secret:
          defaultMode: 420
          secretName: openshift-wildcard-certificate
